# Generated by Django 5.1.1 on 2024-10-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boathistory',
            old_name='star_year',
            new_name='start_year',
        ),
    ]
